# docker-compose.app.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-lists
    ports:
      - "${APP_PORT}:80" # Use APP_PORT from .env
    env_file:
      - ./src/.env
    volumes:
      - ./src:/var/www/html # ⬅️ Mount src as web root
    # environment:
    #   - DB_HOST=${DB_HOST}
