# version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: todo-lists
        ports:
            - "8000:80" # local:container
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        environment:
            - DB_HOST=mysql

    mysql:
        image: mysql:5.7
        container_name: laravel-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: new_laravel
            MYSQL_ROOT_PASSWORD: root

        volumes:
            - mysql_data:/var/lib/mysql
#     phpmyadmin:
#         image: phpmyadmin/phpmyadmin
#         container_name: laravel-phpmyadmin
#         ports:
#             - "8081:80"
#         environment:
#             PMA_HOST: mysql
#             MYSQL_ROOT_PASSWORD: root

volumes:
    mysql_data:
