services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-lists
    ports:
      - "${APP_PORT}:80" # Use APP_PORT from .env
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
